apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kontox-secrets
  namespace: aux-service
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "Kontox-secret"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: kontox-secret
      type: Opaque
      data:
        - objectName: "Kontox-secret"
          key: config
  syncSecret:
    enabled: true
